### ISSUE TITLE
Running init twice fails with S3 bucket problem

### ISSUE THREAD

**Issue by runemadsen** [designsystemsinternational/clis#12]
> ? Which bucket name would you like to use for the lambda ZIP files? elocker-oechsle-integration-operations
⠧ Checking if S3 bucket exists(node:3815) UnhandledPromiseRejectionWarning: Forbidden: null
    at Request.extractError (/Users/bravomartin/.nvm/versions/node/v10.19.0/lib/node_modules/@designsystemsinternational/dynamic/node_modules/aws-sdk/lib/services/s3.js:811:35)
    at Request.callListeners (/Users/bravomartin/.nvm/versions/node/v10.19.0/lib/node_modules/@designsystemsinternational/dynamic/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/bravomartin/.nvm/versions/node/v10.19.0/lib/node_modules/@designsystemsinternational/dynamic/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/bravomartin/.nvm/versions/node/v10.19.0/lib/node_modules/@designsystemsinternational/dynamic/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/bravomartin/.nvm/versions/node/v10.19.0/lib/node_modules/@designsystemsinternational/dynamic/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/bravomartin/.nvm/versions/node/v10.19.0/lib/node_modules/@designsystemsinternational/dynamic/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/bravomartin/.nvm/versions/node/v10.19.0/lib/node_modules/@designsystemsinternational/dynamic/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/bravomartin/.nvm/versions/node/v10.19.0/lib/node_modules/@designsystemsinternational/dynamic/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/bravomartin/.nvm/versions/node/v10.19.0/lib/node_modules/@designsystemsinternational/dynamic/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/Users/bravomartin/.nvm/versions/node/v10.19.0/lib/node_modules/@designsystemsinternational/dynamic/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
(node:3815) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3815) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠼⠋ Checking if S3 bucket exists

**Comment by runemadsen** [comment]
This has been fixed
