### ISSUE TITLE
Error while running static on atap website

### ISSUE THREAD

**Issue by bravomartin** [designsystemsinternational/clis#57]
Ran static deploy on atap-website repo, staging branch. used the static config taken from git history, and got the error below.

When i run it again it fails, and I can't find the stack on the aws console.

```
"static": {
    "profile": "dsi",
    "region": "us-west-1",
    "buildDir": "dist",
    "shouldRunBuildCommand": true,
    "buildCommand": "npm run build",
    "environments": {
      "production": {
        "stack": "atap-website-production",
        "bucket": "atap-website-production",
        "htmlCache": "300",
        "assetsCache": "31536000"
      },
      "production": {
        "stack": "atap-website-production",
        "bucket": "atap-website-production",
        "htmlCache": "300",
        "assetsCache": "31536000"
      }
    }
  }
```

```
> static deploy

? Name of the new Cloudformation stack atap-website-staging
? Enable basic authentication? (requires CloudFront distribution) No
? Enable custom domain? (requires CloudFront distribution and hosted zone ID fro
m Route53) No
? Do you want to set up a Cloudfront distribution? No
? [S3BucketName] Name of the S3 bucket. 
? [IndexPage] Name of the index page. index.html
? [ErrorPage] Name of the error page. index.html
⠇ Creating stackstatic deploy

Deploys the website

Options:
  --version    Show version number                                     [boolean]
  --help       Show help                                               [boolean]
  --env        Ignore current Git branch and use this environment       [string]
  --configure  Reconfigure the CloudFormation stack                    [boolean]
  --confirm    Deploy without confirmation                             [boolean]

ResourceNotReady: Resource is not in the state stackCreateComplete
    at constructor.setError (/Users/bravomartin/WORK/DSI/google/atap-website/node_modules/aws-sdk/lib/resource_waiter.js:182:47)
    at Request.CHECK_ACCEPTORS (/Users/bravomartin/WORK/DSI/google/atap-website/node_modules/aws-sdk/lib/resource_waiter.js:44:12)
    at Request.callListeners (/Users/bravomartin/WORK/DSI/google/atap-website/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/bravomartin/WORK/DSI/google/atap-website/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/bravomartin/WORK/DSI/google/atap-website/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/bravomartin/WORK/DSI/google/atap-website/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/bravomartin/WORK/DSI/google/atap-website/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/bravomartin/WORK/DSI/google/atap-website/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/bravomartin/WORK/DSI/google/atap-website/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/bravomartin/WORK/DSI/google/atap-website/node_modules/aws-sdk/lib/request.js:690:12) {
  code: 'ResourceNotReady',
  retryable: false,
  time: 2020-11-09T23:59:42.941Z,
  statusCode: 200,
  retryDelay: 30000
}
```

**Comment by runemadsen** [comment]
I'm not sure I quite understand. First of all, this is the old `static` config and won't work with the version released 6 months ago. Also, there are two `production` environments in this config and no `staging` environment.

**Comment by bravomartin** [comment]
Will try to reproduce and come back to you
